EDDI-RobotAcademy/next-page

next-page-backend/demo/src/main/java/kr/eddi/demo/utility/encrypt/EncryptionUtil.java
next-page-backend/demo/src/main/java/kr/eddi/demo/utility/encrypt/exception/UnableToGenerateHash.java
next-page-backend/demo/src/main/java/kr/eddi/demo/utility/password/PasswordHashConverter.java
next-page-vue/frontend/src/store/mutation-types.js

22.12.01
회원정보 보안을 위해 정보를 암호화 하는 시스템 구현 [NEXT-PAGE-PROCESS-10]

Feat: [이연경] utility 암호화 구현 [NEXT-PAGE-PROCESS10]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/Authentication.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/BasicAuthentication.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/MemberProfile.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/NextPageMember.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/repository/member/AuthenticationRepository.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/repository/member/MemberRepository.java
next-page-backend/demo/src/main/resources/application.yaml

📚 memeber(회원) entity, repository 생성
📚 MYSQL next_page_db 스키마 생성후 권한 이슈가 발생하여 username 을 eddi 에서 root 로 변경 (application.yaml)

feat: [이연경] entity, repository 생성 [NEXT-PAGE-PROCESS-1]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/MemberController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/MemberProfile.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/NextPageMember.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberServiceImpl.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/member/request/MemberRegisterRequest.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/form/MemberRegisterForm.java
next-page-backend/demo/src/test/java/kr/eddi/demo/member/MemberTest.java

📚 이메일 중복체크 ✔️ [NEXT-PAGE-PROCESS-3]
📚 회원가입 시스템 ✔️[NEXT-PAGE-PROCESS-1]

feat: [이연경] 회원가입 시스템 [NEXT-PAGE-PROCESS-1]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/MemberController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/MemberProfile.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/NextPageMember.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/repository/member/MemberRepository.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberServiceImpl.java
next-page-backend/demo/src/test/java/kr/eddi/demo/member/MemberTest.java

📚 닉네임 중복체크 ✔️[NEXT-PAGE-PROCESS-1]

feat: [이연경] 닉네임 중복체크 [NEXT-PAGE-PROCESS-1]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/MemberController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/repository/member/MemberRepository.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberServiceImpl.java
next-page-backend/demo/src/test/java/kr/eddi/demo/member/MemberTest.java

📚 닉네임 중복체크 일부 변수명 변경 ✔️ [NEXT-PAGE-PROCESS-15]

feat: [이연경] 닉네임 중복체크 일부 변수명 변경 완료 [NEXT-PAGE-PROCESS-15]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/MemberController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberServiceImpl.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/member/request/MemberSignInRequest.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/security/RedisService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/security/RedisServiceImpl.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/form/MemberSignInForm.java
next-page-backend/demo/src/test/java/kr/eddi/demo/member/MemberTest.java

feat: [이연경] 닉네임 중복체크 url 오타 수정 [NEXT-PAGE-PROCESS-15]

---

next-page-backend/demo/build.gradle

init : [이연경] build.gradle(+redis)추가 커밋 [NEXT-PAGE-PROCESS-2]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/novel/NovelController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/NovelService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/NovelServiceImpl.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/entity/NovelCategory.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/entity/NovelCoverImage.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/entity/NovelEpisode.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/entity/NovelInformation.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/form/NovelInformationRegisterForm.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/request/NovelInformationRegisterRequest.java

- NEXT-PAGE-PROCESS-13, NEXT-PAGE-PROCESS-14 관련한 메소드 주석 추가 
- 소설 정보 등록 request와 form 이름 수정 [NEXT-PAGE-PROCESS-13]

add.[한채선] 소설 에피소드 등록 시스템 관련 메소드 주석 추가 [NEXT-PAGE-PROCESS-14]

---

next-page-vue/frontend/src/component/PointCharge/PointChargeForm.vue
next-page-vue/frontend/src/component/Upload/NovelInformationRegisterForm.vue
next-page-vue/frontend/src/router/index.js
next-page-vue/frontend/src/views/Upload/NovelInformationRegisterView.vue

- 소설 정보 등록 ui 구현 [NEXT-PAGE-WEB-UI-11]
- check box를 라디오 버튼으로 수정 [NEXT-PAGE-WEB-UI-8]

feat.[한채선] 소설 정보 등록 ui [NEXT-PAGE-WEB-UI-11]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/repository/member/MemberRepository.java

refactor : [이연경] MemberRepository Query문 이메일 -> 닉네임 으로 수정 [NEXT-PAGE-PROCESS-1]

refactor : [이연경] MemberRepository Query 닉네임 수정 [NEXT-PAGE-PROCESS-1]

---

next-page-flutter/app/lib/main.dart
next-page-flutter/app/lib/member/screens/sign_in_screen.dart
next-page-flutter/app/lib/member/screens/sign_up_screen.dart
next-page-flutter/app/lib/member/widgets/forms/sign_in_form.dart
next-page-flutter/app/lib/mypage/screens/mypage_screen.dart

- 마이페이지 로그인 버튼으로 로그인 페이지로 이동 후 로그인 성공 시 마이페이지로 돌아오는 기능 추가
- 로그인 페이지 app bar 추가
- 회원 가입 페이지 app bar 추가
app bar 추가는 따로 백로그 작성하지 않고 기존에 작성한 백로그 태그를 달았습니다.

update: [윤희지] 회원가입 페이지 앱바 추가 [NEXT-PAGE-APP-UI-2]

---

next-page-flutter/app/lib/member/widgets/alerts/custom_result_and_push_alert.dart
next-page-flutter/app/lib/member/widgets/forms/sign_in_form.dart

회원가입 완료 alert 내부에 쓰인 컴포넌트 버튼을 변경하였습니다.

fix: [윤희지] 회원가입 완료 alert 페이지 이동 버튼 수정 [NEXT-PAGE-APP-UI-2]

---

next-page-vue/frontend/src/component/mypage/qna/QnAList.vue

update :[이연경] QnA 게시글 목록 테이블 tr 추가[NEXT-PAGE-WEB-UI-17]

---

next-page-vue/frontend/src/component/mypage/qna/QnAList.vue
next-page-vue/frontend/src/component/mypage/qna/QnAModify.vue
next-page-vue/frontend/src/component/mypage/qna/QnARead.vue
next-page-vue/frontend/src/component/mypage/qna/QnARegister.vue
next-page-vue/frontend/src/store/index.js
next-page-vue/frontend/src/views/mypage/qna/QnAListView.vue
next-page-vue/frontend/src/views/mypage/qna/QnAModifyView.vue
next-page-vue/frontend/src/views/mypage/qna/QnAReadView.vue
next-page-vue/frontend/src/views/mypage/qna/QnARegisterView.vue

📚 새로 고침 시에도 로그인 상태 유지 기능 추가
📚 package.json 파일은 커밋 안하였습니다!! (npm install --save vuex-persistedstate)로 install 부탁드려요

feat: [이연경] 로그인 상태 유지 기능 추가 [NEXT-PAGE-WEB-UI-3]

---

next-page-vue/frontend/src/component/mypage/qna/QnAList.vue
next-page-vue/frontend/src/component/mypage/qna/QnAModify.vue
next-page-vue/frontend/src/component/mypage/qna/QnARead.vue
next-page-vue/frontend/src/component/mypage/qna/QnARegister.vue
next-page-vue/frontend/src/views/mypage/qna/QnAListView.vue
next-page-vue/frontend/src/views/mypage/qna/QnAModifyView.vue
next-page-vue/frontend/src/views/mypage/qna/QnAReadView.vue
next-page-vue/frontend/src/views/mypage/qna/QnARegisterView.vue

📚 QnA 게시글 목록에서 작성 폼 이동 버튼 크기 수정
📚 QnA 게시글 작성 버튼 변경
📚 QnA 게시글 읽기에서 수정,삭제 라우터에서 버튼으로 변경
📚 QnA 게시글 수정에서 수정 버튼 수정

update: [이연경] QnA 게시글 수정 폼에서 수정 라우 터에서 버튼으로 변경[NEXT-PAGE-WEB-UI-19]

---

next-page-vue/frontend/src/component/header/HeadlineMenuForm.vue
next-page-vue/frontend/src/store/states.js

feat: [이연경] header 메뉴에 로그아웃 기능 추가[NEXT-PAGE-WEB-UI-3]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/MemberController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/NextPageMember.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberServiceImpl.java

update: [이연경] 로그인시 멤버 정보 가져오기[NEXT-PAGE-PROCESS-2]

update: [이연경] 로그인시 멤버 프로필 가져오기[NEXT-PAGE-PROCESS-2]

---

next-page-backend/demo/src/test/java/kr/eddi/demo/member/MemberTest.java

update: [이연경] 로그인 Test 로직 코드수정[NEXT-PAGE-PROCESS-2]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/MemberController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/NextPageMember.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberServiceImpl.java
next-page-backend/demo/src/test/java/kr/eddi/demo/MemberTest.java

📚 회원탈퇴 시스템
📚 memberTest 로직 패키지 위치 변경

feat: [이연경] 회원탈퇴 시스템[NEXT-PAGE-PROCESS-7]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/MemberController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/NextPageMember.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberServiceImpl.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/member/request/MemberNicknameModifyRequest.java
next-page-backend/demo/src/test/java/kr/eddi/demo/MemberTest.java

feat: [이연경] 닉네임 수정 시스템[NEXT-PAGE-PROCESS-6]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/episode_payment/EpisodePaymentController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/episode_payment/entity/EpisodePayment.java
next-page-backend/demo/src/main/java/kr/eddi/demo/episode_payment/repository/EpisodePaymentRepository.java
next-page-backend/demo/src/main/java/kr/eddi/demo/episode_payment/requset/BuyEpisodeRequest.java
next-page-backend/demo/src/main/java/kr/eddi/demo/episode_payment/service/EpisodePaymentService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/episode_payment/service/EpisodePaymentServiceImpl.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/NextPageMember.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/entity/NovelEpisode.java
next-page-backend/demo/src/test/java/kr/eddi/demo/EpisodePaymentTest.java

feat: [윤희지] 소설 에피소드 구매 시스템[NEXT-PAGE-PROCESS-27]

---

next-page-vue/frontend/src/component/sortNovel/SortNovel.vue
next-page-vue/frontend/src/views/HomeView.vue

faet.[이창훈] 로그인 여부와 상관없이 등록된 소설 정렬 UI [NEXT-PAGE-WEB-UI-22]

---

next-page-vue/frontend/src/component/PointCharge/PointChargeForm.vue
next-page-vue/frontend/src/views/Payment/PointChargeView.vue

style: [이연경] 포인트 충전 페이지 + headline + Footer 추가[NEXT-PAGE-WEB-UI-8]

---

next-page-vue/frontend/src/component/Upload/NovelInformationRegisterForm.vue
next-page-vue/frontend/src/views/Upload/NovelInformationRegisterView.vue

update: [이연경] 소설 게시글 작성 UI 수정 [NEXT-PAGE-WEB-UI-11]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/MemberController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/Authentication.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/member/NextPageMember.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/repository/member/AuthenticationRepository.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/MemberServiceImpl.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/member/request/MemberNicknameModifyRequest.java
next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/service/member/request/MemberPasswordModifyRequest.java
next-page-backend/demo/src/test/java/kr/eddi/demo/MemberTest.java

feat: [이연경] 비밀번호 수정 시스템[NEXT-PAGE-PROCESS-5]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/member/entity/NextPageMember.java
next-page-backend/demo/src/main/java/kr/eddi/demo/qna/controller/QnAController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/qna/entity/QnA.java
next-page-backend/demo/src/main/java/kr/eddi/demo/qna/request/QnARequest.java
next-page-backend/demo/src/main/java/kr/eddi/demo/qna/service/QnAService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/qna/service/QnAServiceImpl.java

next page member entity와 QnA 매핑으로 발생한 변경 사항
- QnARequest: memberId 변수 추가
- NextPageMember: QnA와 OneToMany 추가, QnA 리스트 업데이트 메서드 추가
- QnA: NextPageMember ManyToOne 추가, QnA와 매핑된 member의 QnA 리스트 업데이트를 실행하는 메서드 추가
- QnAServiceImpl: QnA 엔티티에 Member 세팅하는 부분 추가.
기타
- QnAService, QnAServiceImpl의 write 메서드 리턴 타입 Boolean으로 변경
- QnAServiceImpl의 repository 변수명 qnaRepository로 변경

chore: [윤희지] QnA 시스템 관련 변경사항 [NEXT-PAGE-PROCESS-20]

---

next-page-flutter/app/lib/mypage/screens/mypage_screen.dart
next-page-flutter/app/lib/mypage/screens/tmp_my_screen.dart

추가 변경사항: 기존 마이페이지의 카드 메뉴 위젯들을 위젯 메서드로 변경

feat: [윤희지] 관리자용 마이페이지 메뉴 UI [NEXT-PAGE-APP-UI-53]

---

next-page-flutter/app/lib/admin/forms/novel_upload_form.dart

add:[김장순] 관리자 계정으로 로그인시 이용 가능한 소설 업로드 페이지 UI [NEXT-PAGE-APP-UI-54]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/comment/controller/CommentController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/comment/entity/Comment.java
next-page-backend/demo/src/main/java/kr/eddi/demo/comment/repository/CommentRepository.java
next-page-backend/demo/src/main/java/kr/eddi/demo/comment/response/CommentResponse.java
next-page-backend/demo/src/main/java/kr/eddi/demo/comment/service/CommentService.java
next-page-backend/demo/src/main/java/kr/eddi/demo/comment/service/CommentServiceImpl.java
next-page-backend/demo/src/main/java/kr/eddi/demo/novel/controller/NovelController.java
next-page-flutter/app/lib/comment/api/comment_reponses.dart
next-page-flutter/app/lib/comment/api/spring_comment_api.dart
next-page-flutter/app/lib/comment/comment_list_screen.dart
next-page-flutter/app/lib/comment/widgets/comment_list_form.dart
next-page-flutter/app/lib/main.dart
next-page-flutter/app/lib/novel/screens/scroll_novel_viewer_screen.dart
next-page-flutter/app/lib/utility/providers/comment_provider.dart

comment list form에 원래 작성되어있던 코드인데 에디터에서 dead code로 인식되는 부분이 있으니 확인 바랍니다!

 [윤희지] spring에 에피소드별 댓글 리스트 정보 요청 api, 기존 UI와 연결 [NEXT-PAGE-APP-UI-57]

---

next-page-flutter/app/lib/comment/api/comment_requests.dart
next-page-flutter/app/lib/comment/api/spring_comment_api.dart
next-page-flutter/app/lib/comment/comment_list_screen.dart
next-page-flutter/app/lib/comment/widgets/comment_list_form.dart
next-page-flutter/app/lib/comment/widgets/comment_text_form.dart
next-page-flutter/app/lib/novel/screens/novel_detail_screen.dart
next-page-flutter/app/lib/novel/screens/scroll_novel_viewer_screen.dart
next-page-flutter/app/lib/widgets/cupertino_result_alert.dart

댓글 등록, 삭제까지 완료.
댓글 수정은 api까지 완료. UI 연결 작업은 아직 진행하지 않음.

feat: [윤희지] 댓글 등록, 수정, 삭제 요청 api, UI 연결 [NEXT-PAGE-APP-UI-58]

---

next-page-flutter/app/lib/admin/forms/novel_modify_form.dart

gesture detector로 키보드 패드 종료시 ui상의 값이 초기화되는 문제 해결

hotfix:[김장순]  소설 정보 수정 페이지 UI [NEXT-PAGE-APP-UI-58]

---

next-page-backend/demo/src/main/java/kr/eddi/demo/comment/controller/CommentController.java
next-page-backend/demo/src/main/java/kr/eddi/demo/comment/service/CommentServiceImpl.java
next-page-backend/demo/src/test/java/kr/eddi/demo/CommentTestCase.java
next-page-flutter/app/lib/mypage/screens/mypage_screen.dart
next-page-flutter/app/lib/notice/api/SpringNoticeApi.dart
next-page-flutter/app/lib/notice/api/notice_requests.dart
next-page-flutter/app/lib/notice/notice_upload_form.dart
next-page-flutter/app/lib/notice/screens/notice_management_screen.dart

누락된 댓글 에피소드 리스트 조회 테스트도 추가했습니다.

feat: [윤희지] qna 답변 댓글 작성 시스템 [NEXT-PAGE-PROCESS-38]

---

next-page-flutter/app/lib/main.dart
next-page-flutter/app/lib/mypage/screens/mypage_screen.dart
next-page-flutter/app/lib/notice/api/notice_requests.dart
next-page-flutter/app/lib/notice/api/notice_responses.dart
next-page-flutter/app/lib/notice/api/spring_notice_api.dart
next-page-flutter/app/lib/notice/notice_upload_form.dart
next-page-flutter/app/lib/notice/screens/common_notice_list_screen.dart
next-page-flutter/app/lib/notice/screens/notice_management_screen.dart
next-page-flutter/app/lib/novel/screens/novel_detail_screen.dart
next-page-flutter/app/lib/novel/widgets/novel_notice.dart
next-page-flutter/app/lib/search/screen/search_screen.dart
next-page-flutter/app/lib/utility/providers/notice_provider.dart

공지사항 작성 페이지에서 커밋 누락된 공지사항 작성 요청 api도 포함됨.

feat: [윤희지] 일반 공지사항 페이지 UI [NEXT-PAGE-APP-UI-64]

---

next-page-flutter/app/lib/member/widgets/forms/sign_up_form.dart

- 알럿 수정 (CustomResultAlert 버튼 cupertinoResultAlert 로 변경 )

style:[이연경] 알럿 UI 수정[NEXT-PAGE-APP-UI-2]

---

next-page-backend/demo/.env.sample
next-page-backend/demo/.gitignore
next-page-backend/demo/Dockerfile
next-page-backend/demo/build.gradle
next-page-backend/demo/docker-compose.yml
next-page-backend/demo/docker/mysql/custom.cnf
next-page-backend/demo/src/main/resources/application.yaml
next-page-backend/demo/src/test/java/kr/eddi/demo/CommentTestCase.java
next-page-backend/demo/src/test/java/kr/eddi/demo/DemoApplicationTests.java
next-page-backend/demo/src/test/java/kr/eddi/demo/EpisodePaymentTest.java
next-page-backend/demo/src/test/java/kr/eddi/demo/FavoriteTestCase.java
next-page-backend/demo/src/test/java/kr/eddi/demo/MemberTest.java
next-page-backend/demo/src/test/java/kr/eddi/demo/NoticeTestCase.java
next-page-backend/demo/src/test/java/kr/eddi/demo/NovelTestCase.java
next-page-backend/demo/src/test/java/kr/eddi/demo/PointChargeTest.java
next-page-backend/demo/src/test/java/kr/eddi/demo/QnaTestCase.java

- Dockerfile
- docker-compose.yml
- .env.example

build: 배포를 위한 최종 docker files 완료
